jobs:
  test:
    image: node:18
    requires: [ ~commit, ~pr, ~sd@12500:hub, ~sd@4410:fail_A ]
    steps:
      - test: echo "foo"
    annotations:
      screwdriver.cd/displayName: "very-long-long-long-long-name"
  test2:
    image: node:18
    requires: [ ~commit, ~pr, ~sd@12500:nothing ]
    steps:
      - test: echo "foo"
    annotations:
      screwdriver.cd/displayName: "very-long-long-long-long-name"
