shared:
  image: node:18
jobs:
  main:
    requires: [ ~commit, ~pr ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - test: echo 'test'
  foo:
    requires: [ main ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - test: echo 'test'
  bar:
    requires: [ main ]
    steps:
      - test: echo 'test'
  baz:
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - test: echo 'test'
