shared:
  image: node:18
jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
      - set: meta set hello "$(date)"
      - test: meta dump | jq -M
  virtual:
    requires: [ main ]
    annotations:
      screwdriver.cd/virtualJob: true
    steps:
      - test: meta dump | jq -M
  third:
    requires: [ virtual ]
    steps:
      - test: meta dump | jq -M
  foo:
    requires: [ ~commit, ~pr ]
    steps:
      - set: meta set date "$(date)"
      - test: meta dump | jq -M
  bar:
    requires: [ foo ]
    steps:
      - test: meta dump | jq -M
  baz:
    requires: [ bar ]
    steps:
      - test: meta dump | jq -M
