shared:
  image: node:20
  steps:
    - hello: echo 'world'

jobs:
  hub:
    requires: [~commit, ~pr]
    steps:
      - wait: sleep 30
  a:
    requires: []
  b:
    requires: []
    steps:
      - fail: exit 1
  c:
    requires: [a]
    steps:
      - wait: sleep 30
  target:
    requires: [~stage@simple]
stages:
  simple:
    requires: [~hub]
    jobs: [a, b]
    teardown:
      image: node:20
      steps:
        - test: echo 'teardown 2'
