shared:
  image: node:20
  steps:
    - hello: echo 'world'
  annotations:
    screwdriver.cd/virtualJob: true

jobs:
  main:
    requires: [ ~pr ]
  a:
    requires: []
  b:
    requires: []
  c:
    requires: [a]
    steps:
      - wait: sleep 30
  d:
    requires: [ main ]
  e:
    requires: [ stage@simple:setup ]
  f:
    requires: [ stage@simple ]

stages:
  simple:
    requires: [ ~pr ]
    jobs: [a, b, c]
