shared:
    image: node:20

jobs:
    main:
        # requires: [ ~pr, ~commit, ~pr-closed ]
        steps:
            - meta: meta set foo bar
        parameters:
          foo: bar
    three:
        requires: [ ~commit, sd@25614:two ]
        steps:
            - meta: echo 'foo'
        annotations:
          screwdriver.cd/virtualJob: true
        settings:
          slack:
            channels:
              - test-default-notification
            statuses:
              - SUCCESS
            message: "Hello! Screwdriver.cd!"
    four:
        requires: [ three ]
        steps:
            - test: meta dump | jq -M
        settings:
          slack:
            channels:
              - test-default-notification
            statuses:
              - SUCCESS
            message: "Hello! Screwdriver.cd!"
stages:
  new:
    jobs: [ main ]
    description: "PR description"
