shared:
  image: node:20
  steps:
    - test: echo 'test'

stages:
  red:
    requires: [ ~hub ]
    description: First stage
    jobs: [ a, b ]

jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    description: empty
  b:
    description: empty
    steps:
      - sleep 60 && exit 1
  target:
    requires: [ ~stage@red ]
