annotations:
  screwdriver.cd/chainPR: false

shared:
  image: node:20
  steps:
    - hello: echo 'world!'

jobs:
  main:
    requires: [ ~pr ]
  a:
    requires: []
    steps:
      - wait: sleep 30
  b:
    requires: []
    # steps:
    #   - fail: exit 1
  c:
    requires: [a]
  d:
    requires: [ main ]
  e:
    requires: [ stage@simple:setup ]
  f:
    requires: [ stage@simple ]

stages:
  simple:
    requires: [ ~pr, ~commit ]
    jobs: [a, b, c]
    setup:
      image: node:20
      steps:
        - init: echo 'integration setup'
    teardown:
      image: node:20
      steps:
        - init: echo 'integration teardown'
