# jobs:
#   main:
#     requires: [ ~commit ]
#     image: node:20
#     steps:
#       - test: echo test
#   join:
#     requires: [ sd@12926:foo, sd@12926:bar ]
#     annotations:
#       screwdriver.cd/virtualJob: true
#     image: node:20
#     steps:
#       - test: echo testaaa
shared:
    image: node:22
    steps:
        - echo: echo "test"

jobs:
    hub:
        requires: [ ~commit, ~pr ]
        annotations:
            screwdriver.cd/virtualJob: true

    a:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.bar "success"

    b:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.baz "success"

    c:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.bar "error"

    d:
        requires: [ ~hub ]
        steps:
            - set: meta set foo.baz "error"

    virtual:
        requires: [ a, b ]
        annotations:
            screwdriver.cd/virtualJob: true

    target:
        requires: [ ~virtual ]
        blockedBy: [ ~c, ~d ]
        steps:
            - print: meta get "foo"
            - check_meta: |
                  test "success" = `meta get "foo.bar"`
                  test "success" = `meta get "foo.baz"`
