shared:
  image: node:18
jobs:
  Job1:
    requires: [ ~commit ]
    steps:
      - meta set x "1"

  Job2:
    requires: [ ~Job1 ]
    steps:
      - meta set x "2"

  Job3:
    requires: [ ~Job1 ]
    steps:
      - meta set x "3"
      - sleep 30

  Job4:
    requires: [ Job2, Job3 ]
    steps:
      - echo $(meta get x)
