shared:
  image: node:20

jobs:
  only:
    requires: [ ~commit, ~pr ]
    steps:
      - echo: echo 'test'
    annotations:
      screwdriver.cd/virtualJob: true
  with-down:
    requires: [ ~commit, ~pr ]
    steps:
      - echo: echo 'test'
    annotations:
      screwdriver.cd/virtualJob: true
  down:
    requires: [ with-down ]
    steps:
      - echo: echo 'test'
