shared:
    image: node:14
    steps:
        - test: echo 'foo'
jobs:
  first:
    requires: [ ~commit ]
    steps:
      - echo: echo 'no wait'
  x-second:
    requires: [ first ]
    steps:
      - echo: echo 'no wait'
  y-second:
    requires: [ first ]
    steps:
      - wait: sleep 30
  y-third:
    requires: [ y-second ]
    steps:
      - echo: echo 'no wait'
  z:
    requires: [ x-second, y-third ]
    steps:
      - echo: echo 'no wait'
