shared:
    image: node:14
    steps:
        - test: echo 'foo'
jobs:
  foo:
    requires: [ ~sd@9550:main ]
    annotations:
      screwdriver.cd/virtualJob: true
  bar:
    requires: [ sd@9550:main ]
    annotations:
      screwdriver.cd/virtualJob: true
