shared:
  image: node:20
  steps:
    - test: echo 'test'

stages:
  red:
    requires: [ ~hub ]
    description: First stage
    jobs: [ a, b, c ]

jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    steps:
      - test: echo 'test'
  b:
    steps:
      - test: echo 'test'
  c:
    requires: [ a, b ]
  d:
    requires: [ ~stage@red ]
