shared:
  image: node:20
  steps:
    - test: echo 'test'
annotations:
  screwdriver.cd/chainPR: true
stages:
  red:
    requires: [ ~hub ]
    description: First stage
    jobs: [ a, b, c, d ]
    teardown:
      steps:
        - test: echo 'foo'

jobs:
  hub:
    requires: [ ~commit ]
  a:
    steps:
      - test: echo 'bar'
  b:
    steps:
      - test: sleep 1
  c:
    requires: [ b ]
  d:
    requires: [ a ]
  target:
    requires: [ ~stage@red, ~aaa ]
  aaa:
    requires: [ ~pr ]
