shared:
    image: node:20

jobs:
    main:
        requires: [ ~pr, ~commit, ~pr-closed ]
        steps:
            - meta: meta set foo bar
        parameters:
          foo: bar
    three:
        requires: [ sd@25614:two ]
        steps:
            - meta: echo 'foo'
        annotations:
          screwdriver.cd/virtualJob: true
    four:
        requires: [ three ]
        steps:
            - test: meta dump | jq -M
