shared:
    image: node:20

jobs:
    main:
        # requires: [ ~pr, ~commit, ~pr-closed ]
        steps:
            - meta: meta set foo bar
        parameters:
          foo: bar
    three:
        steps:
            - meta: echo 'foo'
        annotations:
          screwdriver.cd/virtualJob: true
    four:
        requires: [ three ]
        steps:
            - test: meta dump | jq -M

stages:
  new:
    jobs: [ main ]
    description: "PR description"
  new2:
    jobs: [ three ]
    requires: [ ~pr ]
    description: "PR description"
