jobs:
  main:
    requires: [ ~commit, ~pr ]
    image: node:20
    steps:
      - echo: echo 'test'
    settings:
      slack:
        channels: [ test-default-notification ]
        statuses: [ SUCCESS, FAILURE, QUEUED. RUNNING ]
        message: "foo bar"
