shared:
    image: node:12
jobs:
    A:
        requires: [~pr, B]
        template: nodejs/test@latest
        steps:
            - runA
    B:
        requires: [~pr, ~commit]
        steps:
            - runB
