shared:
  image: node:20
  steps:
    - echo: git log
jobs:
  main:
    requires: [ ~commit, ~pr ]
  test:
    requires: [ ~tag, ~release ]
    environment:
      GIT_SHALLOW_CLONE_SINGLE_BRANCH: true
