jobs:
  one:
    requires: [ sd@20898:main ]
    image: node:20
    # annotations:
    #   screwdriver.cd/virtualJob: true
    steps:
      - test: meta dump
  two:
    requires: [ one ]
    image: node:20
    # annotations:
    #   screwdriver.cd/virtualJob: true
    steps:
      - test: meta dump
