shared:
  image: node:20
  steps:
    - hello: echo 'world'

jobs:
  main:
    requires: [ ~pr ]
  a:
    requires: []
  b:
    requires: []
  c:
    requires: [a]
  d:
    requires: [ main ]
  e:
    requires: [ stage@simple:setup ]
  f:
    requires: [ stage@simple ]

stages:
  simple:
    requires: [ ~pr ]
    jobs: [a, b, c]
  setup:
    image: node:20
    steps:
      - hello: echo 'test'
  teardown:
    image: node:20
    steps:
      - hello: echo 'test'
