shared:
  image: node:20
  steps:
    - echo: |
        git log
        git log 'HEAD^'
annotations:
  screwdriver.cd/chainPR: true
jobs: 
  test: 
    requires: [ ~commit, ~pr ]
    steps: 
      - foo: git log
  # second: 
  #   requires: [ ~test ]
  #   steps: 
  #     - foo: echo 'hoge'
