shared:
  image: node:20
  steps:
    - test: echo 'test'

jobs:
  hub:
    requires: [ ~commit, ~pr ]
    steps:
      - test: sleep 20
  a:
    requires: [ ~hub ]
  b:
    requires: [ ~hub ]
  c:
    requires: [ ~hub ]
  target:
    requires: [ a, b, c ]
