shared:
    image: node:14
    steps:
        - test: echo 'foo'
jobs:
  hub:
    requires: [ ~commit, ~pr ]
  test:
    requires: []
  test2:
    requires: []
  Y2:
    requires: [ ~sd@10:12926, test, test2 ]
