shared:
  image: node:20
  steps:
    - test: echo 'test'
annotations:
  screwdriver.cd/chainPR: true
stages:
  red:
    requires: [ ~hub ]
    description: First stage
    jobs: [ a, b, c, d ]

jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    steps:
      - test: exit 1
  b:
    steps:
      - test: sleep 60
  c:
    requires: [ b ]
  d:
    requires: [ a ]
  target:
    requires: [ ~stage@red ]
