shared:
  image: node:20
  steps:
    - hello: echo 'hello'

jobs:
  hub:
    requires: [~commit, ~pr]
    steps:
      - wait: sleep 30
  a:
    requires: []
  b:
    requires: []
    steps:
      - fail: exit 1
  c:
    requires: [a]
    steps:
      - wait: sleep 30
  target:
    requires: [~stage@simple]
    annotations:
      screwdriver.cd/virtualJob: true
stages:
  simple:
    requires: [~hub]
    jobs: [a, b, c]
    teardown:
      image: cd.docker-registry.corp.yahoo.co.jp:4443/rocky/rocky9-build-base:latest
      steps:
        - test: echo 'teardown'
