jobs:
    test:
        image: cd.docker-registry.corp.yahoo.co.jp:4443/centos/centos7-build-base:latest
        requires: [ ~pr, ~commit ]
        steps:
            - echo: echo 'Hello World'
    deploy:
        image: cd.docker-registry.corp.yahoo.co.jp:4443/centos/centos7-build-base:latest
        settings:
            slack:
                channels:
                    - private-yuokesak
                statuses:
                    - SUCCESS
                    - FAILURE
                    - ABORTED
                    - QUEUED
                    - RUNNING
                minimized: false
        requires: [ test ]
        steps:
            - echo: echo 'Deploy'
    detach:
        image: cd.docker-registry.corp.yahoo.co.jp:4443/centos/centos7-build-base:latest
        steps:
            - echo: echo 'Deploy'
            - failure: meta set meta.status.failure '{"status":"FAILURE","message":"FAILURE!!"}'
            - success: meta set meta.status.success '{"status":"SUCCESS","message":"SUCCESS!!"}'
            - aborted: meta set meta.status.aborted '{"status":"ABORTED","message":"ABORTED!!"}'
            - queued: meta set meta.status.queued '{"status":"QUEUED","message":"QUEUED!!"}'
            - running: meta set meta.status.running '{"status":"RUNNING","message":"RUNNING!!"}'
