shared:
  image: node:20
  steps:
    - hello: echo 'hello'

jobs:
  main:
    requires: [ ~commit, ~pr ]
  job1:
    requires: []
  job2:
    requires: []
  job3:
    requires: []
  target-job-with-long-name:
    requires: [ stage@foo, stage@bar, stage@baz]

stages:
  foo:
    requires: [ ~main ]
    jobs: [ job1 ]
  bar:
    requires: [ ~main ]
    jobs: [ job2 ]
  baz:
    requires: [ ~main ]
    jobs: [ job3 ]
