shared:
  image: node:18
jobs:
  default:
    requires: [ ~commit, ~pr ]
    steps:
      - test: ls sd-pipeline-template-test
  true:
    requires: [ ~commit, ~pr ]
    steps:
      - test: ls sd-pipeline-template-test
    environment:
      GIT_RECURSIVE_CLONE: true
  false:
    requires: [ ~commit, ~pr ]
    steps:
      - test: ls sd-pipeline-template-test
      - clone: git submodule update --init --recursive
      - test2: ls sd-pipeline-template-test
    environment:
      GIT_RECURSIVE_CLONE: false
