jobs:
  main:
    requires: [ ~commit, ~pr ]
    image: node:20
    steps:
      - echo: meta set build.meta.notification.slack.main.message "Overwrite"
    settings:
      slack:
        channels: [ test-default-notification ]
        statuses: [ SUCCESS, FAILURE, QUEUED, RUNNING ]
        message: "foo bar"
