shared:
  image: node:20
  steps:
    - test: echo 'test'

jobs:
  hub:
    requires: [ ~commit, ~pr ]
  a:
    requires: [ ~hub ]
  b:
    requires: [ ~hub ]
    steps:
      - test: |
          var=$(meta get foo)
          if [ "$var" != "true" ]; then
            exit 1
          fi
    parameters:
      foo: "true"
  c:
    requires: [ ~hub ]
    steps:
      - test: sleep 120
  target:
    requires: [ a, b, c ]
