annotations:
  screwdriver.cd/chainPR: true
shared:
  image: node:20
jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
      - test: echo 'test'
  a:
    requires: [ ~main ]
    steps:
      - test: echo 'test'
  b:
    requires: [ ~main ]
    steps:
      - test: meta dump
  c:
    requires: [ a, b ]
    steps:
      - test: meta set foo 'bar'
