annotations:
  screwdriver.cd/chainPR: true
  
jobs:
  main:
    image: node:12
    requires: [ ~commit, ~pr ]
    steps:
      - test: echo "main"
  foo:
    image: node:12
    requires: [ ~pr ]
    steps:
      - test: echo "foo"
  bar:
    image: node:12
    requires: [ foo ]
    steps:
      - test: echo "bar"
