shared:
  image: node:12
  steps:
    - test: echo 'Foo bar'
jobs:
  A:
    requires: [~pr, B, stage@foo]
  B:
    requires: [~pr, ~commit]
  C:
    requires: []
  D:
    requires: []
  E:
    requires: [ C ]

stages:
  foo:
    jobs: [ C, E ]
    setup:
      steps:
        - foo: bar
    teardown:
      steps:
        - foo: bar
  bar:
    jobs: [ D ]
    requires: [ B, A ]
    setup:
      steps:
        - foo: bar
